### ISSUE TITLE
New video file path

### ISSUE THREAD

**Issue by Kevga** [MoistSac/ChroMapper-Cinema#1]
Hey,

cool to see that you made a ChroMapper plugin. I just wanted to let you know that I recently changed the location that WIP videos are stored at, so this plugin will fail to load videos downloaded with the most recent version of Cinema. The videos are now stored in `CustomWIPLevels/CinemaWIPVideos/<MapName>`. I don't have ChroMapper installed and can't make a proper PR, but for your convenience here is some pseudocode for it:

```cs
var mapFolderName = new DirectoryInfo(LevelDir).Name;
var wipDir = Directory.GetParent(LevelDir).FullName;
var videoPath = Path.Combine(wipDir, "CinemaWIPVideos", mapFolderName, videoFile);
```

**Comment by MoistSac** [comment]
Should be fixed in v0.3
